// import "./globals.css";
import Sidebar from '@/Components/Student/Sidebar'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        
        {/* <Sidebar/> */}
        {children}
      </body>
    </html>
  );
}
